version: '3.8'

services:
  web:
    image: mcr.microsoft.com/devcontainers/python:3
    ports:
      - "80:80"
      - "11434:11434"
    volumes:
      - ..:/app
    extra_hosts: 
      - "host.docker.internal:host-gateway"